# Generated by Django 3.1 on 2021-05-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='contentHeader',
            field=models.ImageField(default='blog/%d/', upload_to=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='introPics',
            field=models.ImageField(default='blog/%d/', upload_to=''),
        ),
    ]
