# Generated by Django 3.2 on 2021-05-06 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_posttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='postType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.posttype'),
        ),
    ]
