# Generated by Django 3.2 on 2021-05-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210515_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blogPost2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='extrapics',
        ),
    ]
